Expr ::= Conditional

Conditional ::=
      LogicalOr
    | LogicalOr "?" Expr ":" Conditional

LogicalOr  ::= LogicalAnd ( "||" LogicalAnd )*
LogicalAnd ::= Equality   ( "&&" Equality   )*

Equality   ::= Relational ( ( "==" | "!=" ) Relational )*
Relational ::= Additive   ( ( "<" | ">" | "<=" | ">=" ) Additive )*

Additive       ::= Multiplicative ( ( "+" | "-" ) Multiplicative )*
Multiplicative ::= Exponent       ( ( "*" | "/" | "%" ) Exponent )*

Exponent ::= Unary ( "^" Exponent )?

Unary ::=
      ( "!" | "+" | "-" ) Unary
    | Primary

Primary ::=
      IDENT
    | CONSTANT
    | "(" Expr ")"
